[theme]
theme = "bad-wolf"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
interval = 1
format = "$icon $utilization"

[[block]]
block = "temperature"
interval = 10
format = "CPU: $max"
chip = "coretemp-isa-0000"

[[block]]
block = "temperature"
interval = 30
format = "SSD: $max"
chip = "nvme-pci-0200"

[[block]]
block = "temperature"
interval = 30
format = "WiFi: $max"
chip = "iwlwifi_1-virtual-0"

[[block]]
block = "custom"
command = "echo 'âŒ' $(sensors dell_ddv-virtual-0 2>/dev/null | grep 'CPU Fan' | awk '{print $3, $4}' || echo 'N/A')"
interval = 5

[[block]]
block = "memory"
format = "$icon$mem_used_percents"

[[block]]
block = "disk_space"
path = "/"
format = "$path $available"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

#[[block]]
#block = "disk_space"
#path = "/home"
#format = "$path $available"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 10.0
#alert = 5.0
#
#[[block]]
#block = "disk_space"
#path = "/tmp"
#format = "$path $available"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 10.0
#alert = 5.0

#[[block]]
#block = "disk_space"
#path = "/home/ow/2nd-ssd"
#format = "/2 $available"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 10.0
#alert = 5.0

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency |} $ip $speed_down/$speed_up "

#[[block]]
#block = "net"
#device = "wlp3s0"
#format = "$speed_up/$speed_down"
#ssid = true
#signal_strength =false 
#ip = false
#speed_up = true 
#graph_up = false 
#interval = 5
#
#[[block]]
#block = "networkmanager"
#on_click = "alacritty -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "virbr0"]
#interface_name_include = []
#ap_format = "{ssid^10} {strength}"
#
#[[block]]
#block = "custom"
#command = "timeout .5 dig +short myip.opendns.com @resolver1.opendns.com"
###command = "echo ext. `curl -4 icanhazip.com`"
#interval = 10
# External IP - disabled
#[[block]]
#block = "external_ip"
#format = "$ip"
#[[block]]
#block = "docker"
#interval = 2
#format = "$icon $running/$total"
#
[[block]]
block = "backlight"
device = "intel_backlight"
[[block]]
block = "sound"
#
[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15
#
[[block]]
block = "battery"
driver = "upower"
format = "$icon $percentage $time $power"
#
[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%a %Y-%m-%d %T', l:de_DE)"
#
#[[block]]
#block = "toggle"
#text = ""
#command_state = "xrandr | grep DP3-1\\ connected\\ 38 | grep -v eDP1"
#command_on = "~/.screenlayout/dock.sh"
#command_off = "~/.screenlayout/single.sh"
#interval = 5
